### ISSUE TITLE
Replace alert() with Modal-Based Popup for Better UX

### ISSUE THREAD

**Issue by CODExJATIN** [Navneet1206/Ether-Chess-OTC#1]
The app currently uses alert() for notifications, which is disruptive and lacks customization. Replacing it with a modal-based popup would improve user experience by providing a non-intrusive, customizable notification system.

**Improvement:**
Replace alert() with a modal (e.g., **Material-UI Dialog**) for notifications like **"Game created successfully"** or **"Failed to create game."**
Ensure the modal is dismissible and styled to match the app’s design.

**Benefits:**

- A modal provides a smoother, less intrusive experience and allows users to close it at their convenience.
- It offers greater design flexibility, ensuring the notifications align with the app's overall look and feel.
- The modal improves user interaction by not blocking the interface, making it more seamless and intuitive.

**Location:**
This change primarily affects areas where alert() is used, such as in OnlineMode.jsx.

**I would be happy to work on this and implement the modal-based popups. Could you please assign this issue to me?**

**Comment by Navneet1206** [comment]
Hi @CODExJATIN,

Thank you for bringing up this improvement suggestion. While the primary focus of the app has been on functionality rather than UI enhancements, I agree that replacing `alert()` with a modal-based popup would significantly improve the user experience by making notifications less intrusive and more visually appealing.

I appreciate your initiative in proposing to implement this change. I am assigning this issue to you so you can proceed with the implementation. Please ensure the following:

1. Use a modal library such as Material-UI Dialog or any other library that aligns well with the current tech stack.
2. Ensure the modal is:
   - Dismissible.
   - Consistent with the app's design theme.
3. Replace `alert()` in all relevant sections, particularly in `OnlineMode.jsx`.
4. Test the implementation thoroughly to ensure smooth functionality.

Looking forward to your contribution! Let me know if you need any clarification or assistance.

Best regards,  
Navneet Vishwakarma

**Comment by CODExJATIN** [comment]
Hi @Navneet1206,

Thank you for previously assigning me this issue. I had already started working on implementing the modal-based popup notifications when it was assigned earlier.

As I’m participating in Social Winter of Code (SWOC), I’d like to officially contribute to this issue as part of the event. Would it be possible to reassign this issue to me? I’ll ensure it aligns with the app’s design theme and meets the outlined requirements.

Additionally, since SWOC contributions begin after January 1st, I’ll continue my work from then to ensure it’s counted under the event guidelines.

Looking forward to your response!

Best regards,
CODExJATIN

**Comment by Navneet1206** [comment]
Hey @CODExJATIN ,

Thank you for showing interest in contributing! Please go ahead and hit the Start button to get started on the task. Let me know if you have any questions or need any guidance along the way.

Looking forward to your contributions!

Best regards,
Navneet Vishwakarma

**Comment by Navneet1206** [comment]
> Hey @CODExJATIN ,
> 
> Thank you for showing interest in contributing! Please go ahead and hit the Start button to get started on the task. Let me know if you have any questions or need any guidance along the way.
> 
> Looking forward to your contributions!
> 
> Best regards, Navneet Vishwakarma

@CODExJATIN

**Comment by Navneet1206** [comment]
Hi @CODExJATIN ,

Thank you for showing interest in contributing! I resolved this issue, but now we can't move on. So, I am requesting you to fix another issue.

Looking forward to your contributions!

Best regards,
Navneet Vishwakarma
