### ISSUE TITLE
Navbar and Footer

### ISSUE THREAD

**Issue by Priyanshiagarwal2006** [Navneet1206/Ether-Chess-OTC#8]
1. Add a navbar at the top with a clean UI, featuring the Chessed logo and the name 'Chessed' written on the left side.
2. Include a footer at the bottom of the page with useful information or links (e.g., copyright info, contact links).

**Comment by Navneet1206** [comment]
Hi @Priyanshiagarwal2006,

I agree that the enhancement in the navbar is needed, especially for medium to small-screen devices, as the lack of a toggle button, rollback button, or footer can affect the user experience. However, as I’m currently focusing on the Online Mode feature—since it directly ties into monetization—I’m prioritizing that for now.

That being said, I’ll definitely keep your suggestion in mind for future improvements once the core functionality is solid!

Thanks for your understanding and for your contributions!

Best regards,
Navneet Vishwakarma

**Comment by Navneet1206** [comment]
Hey @Priyanshiagarwal2006  ,

Thank you for showing interest in contributing! Please go ahead and hit the Star ✨ button on the repo to show your support. Let me know if you have any questions or need any guidance along the way.

Looking forward to your contributions!

Best regards,
Navneet Vishwakarma

**Comment by Navneet1206** [comment]
Hi @Priyanshiagarwal2006,

Thank you for your hard work on this project! I wanted to let you know that I’ve just resolved the issue with the Navbar, and I’ll be working on the footer in the next hour.

I truly appreciate your understanding and all the contributions you’ve made!

Best regards,

Navneet Vishwakarma

**Comment by Priyanshiagarwal2006** [comment]
so ,it is considered or not as my contribution in swoc?

**Comment by Navneet1206** [comment]
> so ,it is considered or not as my contribution in swoc?
> 

Yes it will be. But main contribution occurred when you change in the code.

**Comment by Priyanshiagarwal2006** [comment]
ok , thankyou!!
