### ISSUE TITLE
Improve the UI of Four-Player Chess Game

### ISSUE THREAD

**Issue by Priyanshiagarwal2006** [Navneet1206/Ether-Chess-OTC#9]
Hi @Navneet1206 
Add a dropdown menu that allows users to select from a variety of chessboard color schemes (e.g., classic black-and-white, wood-themed, or custom color combinations). This feature will let players choose their preferred board style, enhancing their gameplay experience. This should be dynamic in nature and the player can change the color of the chess board even when playing. I’m confident I can resolve this and contribute to improving the user experience.

Thank You!

**Comment by Navneet1206** [comment]
Hi @Priyanshiagarwal2006 ,

Thank you for your suggestion! Yes, this is a valid issue, and I appreciate your input. However, I’m currently focusing more on the **application's functionality Like Socket.io and contract** rather than the UI, as I want to ensure that the core features are smooth and user-friendly first. That said, I agree that improving the user experience through UI enhancements like the color scheme dropdown is a great idea and could be a valuable addition in the future.

Looking forward to your contributions!

Best regards,
Navneet Vishwakarma
